# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0
services:
  hydra:
    environment:
      - STRATEGIES_ACCESS_TOKEN=jwt # Enable JWT tokens by default
      - OAUTH2_TOKEN_HOOK_URL=http://token-hook:4475
      - LOG_LEAK_SENSITIVE_VALUES=true # Debugging output
  token-hook:
    image: token-hook:latest
    container_name: token-hook
    environment:
      - CLAIM_SET_ORIGIN_STARGATE=https://stargate.example.url
      - CLAIM_SET_ORIGIN_ZONE=example-zone
      - CLAIM_ADD_AZP=true
      - DEBUG=true
    ports:
      - "4475:4475"
    restart: unless-stopped
    networks:
      - intranet